using AdventOfCode2024.Problems;
using System.Diagnostics;

// var day1p1 = await Day1.RunPart1Async();
// Console.WriteLine("Day 1 Part 1: " + day1p1);
// var day1p2 = await Day1.RunPart2Async();
// Console.WriteLine("Day 1 Part 2: " + day1p2);
// var day2p1 = await Day2.RunPart1Async();
// Console.WriteLine("Day 2 Part 1: " + day2p1);
// var day2p2 = await Day2.RunPart2Async();
// Console.WriteLine("Day 2 Part 2: " + day2p2);
// var day3p1 = await Day3.RunPart1Async();
// Console.WriteLine("Day 3 Part 1: " + day3p1);
// var day3p2 = await Day3.RunPart2Async();
// Console.WriteLine("Day 3 Part 2: " + day3p2);
// var day3 = (await Day3Better.Create()).RunRegex();
// Console.WriteLine(day3);
// var day4 = (await Day4.Create()).Part1();
// Console.WriteLine("Day 4 Part 1: " + day4 + Environment.NewLine);
// var day4p2 = (await Day4.Create()).Part2();
// Console.WriteLine("Day 4 Part 2: " + day4p2 + Environment.NewLine);
// var day5 = await Day5.BetterPart1Async();
// Console.WriteLine("Day 5 Part 1: " + day5);
// var day5p2 = await Day5.Part2Async();
// Console.WriteLine("Day 5 Part 2: " + day5p2);
//var day6 = await Day6.Part1Async();
//Console.WriteLine("Day 6 Part 1: " + day6);
//var day7 = await Day7.Part1Async();
//Debug.WriteLine(day7);
//var day8 = await Day8.Part1Async();
//Debug.WriteLine(day8);
//var day8p2 = await Day8.Part2Async();
//Debug.WriteLine(day8p2);
var day9 = Day9.Part1();
Console.WriteLine(day9);

// var summary = BenchmarkRunner.Run<Benchmarks>();